/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guepunya.personalscheduling.view;

import com.guepunya.personalscheduling.core.Data2;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Willy Sianturi!
 */
public class InputDataView extends javax.swing.JPanel {

    /**
     * Creates new form InputDataView
     */
    public InputDataView() {
        initComponents();
        initView();
    }

    private void initView(){
        lblDosen.setText("");
        lblMakul.setText("");
        lblRuang.setText("");
        lblkromosom.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    public Data2 prosesData = new Data2();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOptimasi = new javax.swing.JButton();
        btTraceProgram = new javax.swing.JButton();
        bawah = new javax.swing.JPanel();
        btGenerateKristal = new javax.swing.JButton();
        Atas = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        btMakul = new javax.swing.JButton();
        btDosen = new javax.swing.JButton();
        btRuang = new javax.swing.JButton();
        btKromosom = new javax.swing.JButton();
        middle = new javax.swing.JPanel();
        txtmakul = new javax.swing.JTextField();
        txtdosen = new javax.swing.JTextField();
        txtruang = new javax.swing.JTextField();
        txtkristal = new javax.swing.JTextField();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tengah = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kanan = new javax.swing.JPanel();
        lblMakul = new javax.swing.JLabel();
        lblDosen = new javax.swing.JLabel();
        lblRuang = new javax.swing.JLabel();
        lblkromosom = new javax.swing.JLabel();

        btOptimasi.setText("Optimasi");
        btOptimasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOptimasiActionPerformed(evt);
            }
        });

        btTraceProgram.setText("Trace Program");
        btTraceProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTraceProgramActionPerformed(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());

        bawah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bawah.setLayout(new java.awt.GridLayout(1, 3));

        btGenerateKristal.setText("Generate Jadwal");
        btGenerateKristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateKristalActionPerformed(evt);
            }
        });
        bawah.add(btGenerateKristal);

        add(bawah, java.awt.BorderLayout.PAGE_END);

        Atas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Masukan Data"));
        Atas.setLayout(new java.awt.BorderLayout());

        right.setLayout(new java.awt.GridLayout(4, 0));

        btMakul.setText("Enter");
        btMakul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMakulActionPerformed(evt);
            }
        });
        right.add(btMakul);

        btDosen.setText("Enter");
        btDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDosenActionPerformed(evt);
            }
        });
        right.add(btDosen);

        btRuang.setText("Enter");
        btRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRuangActionPerformed(evt);
            }
        });
        right.add(btRuang);

        btKromosom.setText("Enter");
        btKromosom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKromosomActionPerformed(evt);
            }
        });
        right.add(btKromosom);

        Atas.add(right, java.awt.BorderLayout.EAST);

        middle.setLayout(new java.awt.GridLayout(4, 0));

        txtmakul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmakulActionPerformed(evt);
            }
        });
        middle.add(txtmakul);

        txtdosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdosenActionPerformed(evt);
            }
        });
        middle.add(txtdosen);

        txtruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtruangActionPerformed(evt);
            }
        });
        middle.add(txtruang);

        txtkristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkristalActionPerformed(evt);
            }
        });
        middle.add(txtkristal);

        Atas.add(middle, java.awt.BorderLayout.CENTER);

        left.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setText("Banyak Kegiatan   :");
        left.add(jLabel1);

        jLabel2.setText("Banyak Penjadwal :");
        left.add(jLabel2);

        jLabel3.setText("Banyak Tempat     :");
        left.add(jLabel3);

        jLabel4.setText("Kristal                    :");
        left.add(jLabel4);

        Atas.add(left, java.awt.BorderLayout.WEST);

        add(Atas, java.awt.BorderLayout.PAGE_START);

        Tengah.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Data"));
        Tengah.setLayout(new java.awt.GridLayout(1, 2));

        kiri.setLayout(new java.awt.GridLayout(4, 0));

        jLabel5.setText("Kegiatan    :");
        kiri.add(jLabel5);

        jLabel6.setText("Penjadwal  :");
        kiri.add(jLabel6);

        jLabel7.setText("Tempat      :");
        kiri.add(jLabel7);

        jLabel8.setText("Kristal        :");
        kiri.add(jLabel8);

        Tengah.add(kiri);

        kanan.setLayout(new java.awt.GridLayout(4, 0));

        lblMakul.setText("Kegiatan    :");
        kanan.add(lblMakul);

        lblDosen.setText("Penjadwal  :");
        kanan.add(lblDosen);

        lblRuang.setText("Tempat      :");
        kanan.add(lblRuang);

        lblkromosom.setText("Kristal        :");
        kanan.add(lblkromosom);

        Tengah.add(kanan);

        add(Tengah, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtdosen() {
        return txtdosen;
    }

    public void setTxtdosen(JTextField txtdosen) {
        this.txtdosen = txtdosen;
    }

    public JTextField getTxtkristal() {
        return txtkristal;
    }

    public void setTxtkristal(JTextField txtkromosom) {
        this.txtkristal = txtkromosom;
    }

    public JTextField getTxtmakul() {
        return txtmakul;
    }

    public void setTxtmakul(JTextField txtmakul) {
        this.txtmakul = txtmakul;
    }

    public JTextField getTxtruang() {
        return txtruang;
    }

    public void setTxtruang(JTextField txtruang) {
        this.txtruang = txtruang;
    }

    private void btMakulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMakulActionPerformed
        // TODO add your handling code here:        
        if (txtmakul.getText().trim().length() <= 0 || txtmakul.getText() == null){
            JOptionPane.showMessageDialog(null, "Jumlah Mata Kuliah Tidak Boleh Kosong");
        }else{
            prosesData.insertDataMakul(this);
            lblMakul.setText(prosesData.getLabelMakul());
        }
    }//GEN-LAST:event_btMakulActionPerformed

    private void btDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDosenActionPerformed
        // TODO add your handling code here:
        if (txtdosen.getText().trim().length() <=0 || txtdosen.getText() == null){
            JOptionPane.showMessageDialog(null, "Jumlah DOsen tidak boleh kosong");
        }else{
            prosesData.insertDataDosen(this);
            lblDosen.setText(prosesData.getLabelDosen());
        }
    }//GEN-LAST:event_btDosenActionPerformed

    private void btRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRuangActionPerformed
        // TODO add your handling code here:
        if (txtruang.getText().trim().length() <= 0 || txtruang.getText() == null){
            JOptionPane.showMessageDialog(null, "Jumlah Ruang tidak boleh kosong");
        }else{
            prosesData.insertDataRuang(this);
            lblRuang.setText(prosesData.getLabelRuang());
        }
    }//GEN-LAST:event_btRuangActionPerformed

    private void btKromosomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKromosomActionPerformed
        // TODO add your handling code here:
        if (txtkristal.getText().trim().length() <=0 || txtkristal.getText() == null){
            JOptionPane.showMessageDialog(null, "Jumlah Kristal Tidak Boleh Kosong");
        }else{
            prosesData.insertDataKristal(this);
            lblkromosom.setText(prosesData.getLabelKristal());
        }
    }//GEN-LAST:event_btKromosomActionPerformed
               
    private void btGenerateKristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateKristalActionPerformed
        /*prosesKromosom = new CreateKromosome(prosesData.getIntKromosom(), prosesData.getDosen(), prosesData.getMakul(), prosesData.getRuang(), prosesData.getIntMakul(), prosesData.getIntDosen(), prosesData.getIntRuang(), prosesData.getTempDosen(), prosesData.getTempMakul(), prosesData.getTempRuang());
        prosesKromosom.buatTabel();*/
        prosesData.buatKristal();
        prosesData.tampilKristalAwal();
        prosesData.buatTabel();
    }//GEN-LAST:event_btGenerateKristalActionPerformed

    private void btOptimasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOptimasiActionPerformed
        // TODO add your handling code here:
        prosesData.optimasi();
        //prosesData.tampilValueGen();
    }//GEN-LAST:event_btOptimasiActionPerformed

    private void btTraceProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTraceProgramActionPerformed
        // TODO add your handling code here:
        prosesData.traceData();
    }//GEN-LAST:event_btTraceProgramActionPerformed

    private void txtmakulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmakulActionPerformed
        // TODO add your handling code here:
        btMakul.doClick();
    }//GEN-LAST:event_txtmakulActionPerformed

    private void txtdosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdosenActionPerformed
        // TODO add your handling code here:
        btDosen.doClick();
    }//GEN-LAST:event_txtdosenActionPerformed

    private void txtruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtruangActionPerformed
        // TODO add your handling code here:
        btRuang.doClick();
    }//GEN-LAST:event_txtruangActionPerformed

    private void txtkristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkristalActionPerformed
        // TODO add your handling code here:
        btKromosom.doClick();
    }//GEN-LAST:event_txtkristalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atas;
    private javax.swing.JPanel Tengah;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDosen;
    private javax.swing.JButton btGenerateKristal;
    private javax.swing.JButton btKromosom;
    private javax.swing.JButton btMakul;
    private javax.swing.JButton btOptimasi;
    private javax.swing.JButton btRuang;
    private javax.swing.JButton btTraceProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JLabel lblDosen;
    private javax.swing.JLabel lblMakul;
    private javax.swing.JLabel lblRuang;
    private javax.swing.JLabel lblkromosom;
    private javax.swing.JPanel left;
    private javax.swing.JPanel middle;
    private javax.swing.JPanel right;
    private javax.swing.JTextField txtdosen;
    private javax.swing.JTextField txtkristal;
    private javax.swing.JTextField txtmakul;
    private javax.swing.JTextField txtruang;
    // End of variables declaration//GEN-END:variables
}
